# Generated by Django 5.2.7 on 2026-02-24 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'Free Account'), ('premium', 'Premium Account')], max_length=20, unique=True)),
                ('duration_days', models.PositiveIntegerField(default=0, help_text='Duration in days. Use 0 for free/lifetime plans.')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('benefits', models.TextField(blank=True, help_text="Displayed to users (e.g., 'Read 2 chapters', 'Unlimited access')")),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Subscription Type',
                'verbose_name_plural': 'Subscription Types',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='profile/default.jpeg', upload_to='profile/')),
                ('subscription_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasers.subscriptiontype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
