# Generated by Django 5.2.7 on 2026-02-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontype',
            name='duration_days',
            field=models.CharField(choices=[(30, 'One Month'), (356, 'One Year')], default=0, help_text='Duration in days. Use 0 for free/lifetime plans.', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='name',
            field=models.CharField(choices=[('free', 'Free Account'), ('premium', 'Premium Account')], max_length=20),
        ),
    ]
