# Generated by Django 5.2.7 on 2025-11-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontype',
            name='name',
            field=models.CharField(choices=[('Free Account', 'Free Account'), ('Premium Account', 'Premium Account')], max_length=50),
        ),
    ]
