# Generated by Django 5.2.7 on 2025-11-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasers', '0002_alter_subscriptiontype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(default='profile/default.jpeg', upload_to='profile/'),
        ),
    ]
