# Generated by Django 5.2.7 on 2025-11-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasers', '0003_alter_userprofile_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptiontype',
            options={'verbose_name': 'Subscription Type', 'verbose_name_plural': 'Subscription Types'},
        ),
        migrations.RemoveField(
            model_name='subscriptiontype',
            name='duration',
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='duration_days',
            field=models.PositiveIntegerField(default=0, help_text='Duration in days. Use 0 for free/lifetime plans.'),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='benefits',
            field=models.TextField(blank=True, help_text="Displayed to users (e.g., 'Read 2 chapters', 'Unlimited access')"),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='name',
            field=models.CharField(choices=[('free', 'Free Account'), ('premium', 'Premium Account')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
