# Generated by Django 5.2.7 on 2026-02-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasers', '0003_alter_subscriptiontype_duration_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontype',
            name='duration_days',
            field=models.CharField(choices=[('30', 'One Month'), ('365', 'One Year')], default='0', help_text='Duration in days. Use 0 for free/lifetime plans.', max_length=20),
        ),
    ]
