# Generated by Django 5.2.7 on 2026-02-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('non_fiction', 'Non-Fiction'), ('mystery', 'Mystery'), ('science_fiction', 'Science Fiction'), ('fantasy', 'Fantasy'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('biography', 'Biography'), ('self_help', 'Self-Help'), ('history', 'History'), ('other', 'Other')], default='other'),
        ),
        migrations.AlterField(
            model_name='book',
            name='accessibility',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='premium'),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
