# Generated by Django 5.2.7 on 2025-10-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(default='profile/default.jpeg', upload_to='profile/'),
        ),
    ]
