# Generated by Django 5.2.7 on 2026-02-12 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasers', '0001_initial'),
        ('readers', '0002_alter_book_genre_alter_book_accessibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library', to='purchasers.userprofile'),
        ),
    ]
