# Generated by Django 5.2.7 on 2025-10-21 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0002_userprofile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ai_image',
            field=models.ImageField(blank=True, null=True, upload_to='ai_images/'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='accessibility',
            field=models.CharField(choices=[('Free', 'Free'), ('Premium', 'Premium')], max_length=20),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='readers.book')),
            ],
        ),
    ]
