# Generated by Django 5.2.7 on 2025-10-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0003_book_ai_image_book_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
