# Generated by Django 5.2.7 on 2025-10-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0005_remove_book_author_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ai_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/ai_images/'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(default='media/profile/default.jpeg', upload_to='media/profile/'),
        ),
    ]
