# Generated by Django 5.2.7 on 2025-11-12 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0006_alter_book_ai_image_alter_genre_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='subscription_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='SubscriptionType',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
