# Generated by Django 5.2.7 on 2025-11-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0007_remove_userprofile_subscription_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ai_image',
        ),
        migrations.AddField(
            model_name='chapter',
            name='ai_image',
            field=models.ImageField(blank=True, null=True, upload_to='ai_images/'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='accessibility',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='premium', max_length=20),
        ),
    ]
