# Generated by Django 5.2.7 on 2025-11-29 05:12

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0008_remove_book_ai_image_chapter_ai_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['chapter_number']},
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('book', 'chapter_number')},
        ),
        migrations.AddField(
            model_name='book',
            name='cover_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(default=1, help_text='Upload PDF or EPUB file', upload_to='readers/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'epub'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='images_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='processing_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='illustration',
            field=models.ImageField(blank=True, help_text='AI-generated chapter illustration', null=True, upload_to='readers/chapters/'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='illustration_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='AI-generated book cover', null=True, upload_to='readers/covers/'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='ai_image',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='content',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('fiction', 'Fiction'), ('non_fiction', 'Non-Fiction'), ('mystery', 'Mystery'), ('science_fiction', 'Science Fiction'), ('fantasy', 'Fantasy'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('biography', 'Biography'), ('self_help', 'Self-Help'), ('history', 'History'), ('other', 'Other')], max_length=50),
        ),
    ]
