# Generated by Django 5.2.7 on 2025-11-29 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0009_alter_book_options_alter_chapter_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
