# Generated by Django 5.2.7 on 2025-11-30 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0010_delete_author_delete_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterIllustration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illustration', models.ImageField(help_text='AI-generated chapter illustration', upload_to='readers/chapters/')),
                ('illustration_prompt', models.TextField(blank=True)),
                ('variation_number', models.PositiveIntegerField(default=1)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illustrations', to='readers.chapter')),
            ],
            options={
                'ordering': ['variation_number'],
                'unique_together': {('chapter', 'variation_number')},
            },
        ),
    ]
