# Generated by Django 5.2.7 on 2025-11-30 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0011_chapterillustration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChapterIllustration',
        ),
    ]
