# Generated by Django 5.2.7 on 2026-01-29 23:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasers', '0004_alter_subscriptiontype_options_and_more'),
        ('readers', '0013_bookrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('progress', models.FloatField(default=0.0, help_text='Reading progress as a percentage', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to='readers.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_history', to='purchasers.userprofile')),
            ],
            options={
                'ordering': ['-last_read_at'],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
