# Generated by Django 5.2.7 on 2026-01-29 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0014_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-last_read_at'], 'verbose_name': 'History', 'verbose_name_plural': 'Histories'},
        ),
    ]
