# Generated by Django 5.2.7 on 2026-01-30 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasers', '0004_alter_subscriptiontype_options_and_more'),
        ('readers', '0015_alter_history_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.ManyToManyField(blank=True, related_name='in_libraries', to='readers.book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library', to='purchasers.userprofile')),
            ],
        ),
    ]
