# Generated by Django 5.2.7 on 2026-01-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0017_genre_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('fiction', 'Fiction'), ('non_fiction', 'Non-Fiction'), ('mystery', 'Mystery'), ('science_fiction', 'Science Fiction'), ('fantasy', 'Fantasy'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('biography', 'Biography'), ('self_help', 'Self-Help'), ('history', 'History'), ('other', 'Other')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
