# Generated by Django 5.2.7 on 2026-01-30 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0019_genre_alter_book_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name': 'Library', 'verbose_name_plural': 'Libraries'},
        ),
    ]
